New landing - Music Festival
decentraland/musicfestival pull request #11
Opened 2024-10-23 16:04 UTC by IsidoroAros

2024-10-23 19:01 UTC, cyaiox commented on src/img/artists/Daniel-Allan.png
is this img duplicated?

`src/img/artists/pictures/Daniel-Allan.png`

2024-10-23 19:08 UTC, cyaiox commented on src/css/fonts.css
> +/* @import url("https://fonts.cdnfonts.com/css/nasalization-2"); */
do you mind removing these comments?

2024-10-23 19:14 UTC, cyaiox commented on src/components/Modal/Index.tsx
> +// const PlanetIco = styled.div`
same here. Do you mind removing these comments?

2024-10-23 19:21 UTC, cyaiox commented on src/components/Marquee/Marquee.tsx
> +        {Array.from({ length: 10 }).map((_, index) => (
np: Depends on how big the screen is, 5 items look enough for the loop

2024-10-23 19:21 UTC, cyaiox commented on src/components/MapComponent/MapComponent.tsx
> +// import mapData from "../../data/mapData.json"
same here, do you mind removing these comments?

2024-10-23 19:22 UTC, cyaiox commented on src/components/LiveTalks/data.ts
> +// import diaUnoCharlaUno from "../../img/liveTalks/Day1charla1.jpg"
same here, do you mind removing these comments?

2024-10-23 19:23 UTC, cyaiox commented on src/components/LineUp/index.tsx
> +// import rightDiamond from "../img/music-festival/right-diamond.png"
```suggestion
```

2024-10-23 19:24 UTC, cyaiox commented on src/components/LineUp/index.tsx
> +  // "16:00",
are these time slots still required?

2024-10-23 19:27 UTC, cyaiox commented on src/components/Faq/Faq.tsx
> +const FaqContainer = styled.div`
np: what do you think about moving these styled components to a `Faq.styled.ts` file?

2024-10-23 19:31 UTC, cyaiox commented on src/components/Exhibitors/Exhibitors.tsx
> +              {/* <p>[{exhibitor.location}]</p> */}
```suggestion
```

2024-10-23 19:35 UTC, cyaiox commented on src/components/DCLMusicInfo/DCLMusicInfo.tsx
>    gap: 8px;
```suggestion
  gap: 8px;
  align-items: baseline;
```
current styles:
<img width="907" alt="image" src="https://github.com/user-attachments/assets/f7749ea5-026b-4475-b26b-9f25187b0aff">


using `align-items: baseline;`:
<img width="918" alt="image" src="https://github.com/user-attachments/assets/161d6612-9649-46a7-88c3-08e9f3309ecd">

2024-10-23 19:38 UTC, cyaiox commented on src/components/Faq/Faq.tsx
> +      {[
np: what do you think about moving these elements to a 
```
const faqs = useMemo(() => [{}, {}, {}, ...{}], [])
```
?

2024-10-23 19:50 UTC, cyaiox commented on src/components/LineUp/index.tsx
> +                <TimeText>{parseInt(time) - 7}:00 PST</TimeText>
when `time >= 0 && time < 7`, the hour is negative

const convertToPST(int hour) => hour >= 7 ? (hour - 7) : ((hour + 24) - 7);

2024-10-23 19:52 UTC, cyaiox requested changes
Overall looking good, left some small comments and it is required to fix the lineup hours

2024-10-23 19:52 UTC, cyaiox commented on src/components/LineUp/index.tsx
> +                <TimeText>{parseInt(time) - 7}:00 PST</TimeText>
when time >= 0 && time < 7, the hour is negative

const convertToPST(int hour) => hour >= 7 ? (hour - 7) : ((hour + 24) - 7);

2024-10-24 08:17 UTC, IsidoroAros commented on src/components/Faq/Faq.tsx
> +      {[
Why should we use a memoizing func without any props that could lead to re-renders?

2024-10-24 10:26 UTC, cyaiox approved these changes

2024-10-24 12:32 UTC, merged